###Traer posteos
GET http://localhost:3000/api/posteos

###Crear posteo
POST http://localhost:3000/api/posteos
Content-Type: application/json

{
   "title" : "quinto titulo",
   "content": "quinto posteo",
   "url_image": "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg"
}

###Modificar posteo
PUT http://localhost:3000/api/posteos/4
Content-Type: application/json

{
   "title" : "cuarto titulo",
   "content": "cuarto posteo",
   "url_image": "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg"
}

###Eliminar posteo
DELETE http://localhost:3000/api/posteos/5
