###Traer posteos
GET http://localhost:3000/api/posteos

###Crear posteo
POST http://localhost:3000/api/posteos
Content-Type: application/json

{
   "title" : "nuevo titulo",
   "content": "nuevo posteo",
   "url_image": "www.google.com"
}

###Modificar posteo
PUT http://localhost:3000/api/posteos/6
Content-Type: application/json

{
   "title" : "hola id 6",
   "content": "nuevo posteo",
   "url_image": "www.url.com"
}

###Eliminar posteo
DELETE http://localhost:3000/api/posteos/3
